version: latest

#volumes:
#	db_volume:

services:
	postres:
		image: postgres
		restart:  always
		environment:
			- TZ=Europe/Moscow
			- POSTGRES_USER: "${POSTGRES_USER}"
			- POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
			- POSTGRES_DB: "${POSTGRES_DB}"
		ports:
			- 5432:5432
		volumes:
			- .:/code
