version: latest

#volumes:
#	db_volume:

services:
  postgres:
    image: postgres
    restart:  always
    environment:
      TZ: Europe/Moscow
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      PGDATA: "/var/lib/postgresql/data/pg_data"
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - '.:/var/lib/postgresql/data'
